our:
    merge_method: 'average'
    init_random: false
    init_first_adapter: true
    trim_rate: 0.0
    use_centroid_map: true
    limit_centroid_map: 10

exp:
    dataset: 'cifar224'
    shuffle: true

    name: 'acmap'
    use_init_ptm: false
    backbone_type: 'vit_base_patch16_224_in21k'

    batch_size: 48
    init_lr: 0.025
    later_lr: 0.025
    weight_decay: 0.0005
    min_lr: 0
    num_workers: 8

    scheduler: 'cosine'
    optimizer: 'sgd'

    init_epochs: 20
    later_epochs: 20

block:
    dim: 768
    dropout: 0.0
    mlp_ratio: 4.0
    ffn_adapt: true
    ffn_option: 'parallel' # parallel | sequential

adapter:
    dropout: 0.1
    d_model: 768
    down_size: 64
    scalar: 0.1
    layernorm_option: 'none' # none | in | out

attention:
    num_heads: 12
    qkv_bias: true
    attn_drop: 0.0
    proj_drop: 0.0

transformer:
    global_pool: false
    num_classes: 0
    embed_dim: 768
    out_dim: 768
    distilled: false
    img_size: 224
    patch_size: 16
    in_chans: 3
    depth: 12
    drop_rate: 0.0
    drop_path_rate: 0.0
    vpt_on: false
    vpt_num: 0
